### PR TITLE
Bump runtime to 42 and update warpinator to 1.2.12

### LINKED ISSUE #5: Warpinator uses an old flatpak runtime
Hello!

It seems warpinator currently uses a really old gnome runtime that stopped being supported almost a year ago. Any chance we can get this updated to use the current gnome runtime instead?

### PR DESCRIPTION
**Pull request by bbhtt**
- Add rust-sdk extension and cargo manifest for cryptography
- Restructure python modules
- Update python-xapp to 2.2.2 and xapp to 2.2.13

Fixes https://github.com/flathub/org.x.Warpinator/issues/5

Ping @mtwebster, please review when you have time, thanks!

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
> Build [101550 failed](https://buildbot.flathub.org/#/builders/32/builds/101550)

`bwrap: Can't get type of source /run/user/995/.flatpak/2385422022: No such file or directory` This is probably an error in the builder.

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
> Build [101589 successful](https://buildbot.flathub.org/#/builders/32/builds/101589) 

Any ideas about this? I believe I built cryptography correctly.

```
Traceback (most recent call last):
  File "/app/libexec/warpinator/warpinator.py", line 1062, in start_network_monitor
    self.new_server()
  File "/app/libexec/warpinator/warpinator.py", line 1122, in new_server
    try_to_start();
  File "/app/libexec/warpinator/warpinator.py", line 1102, in try_to_start
    auth_singleton.update(self.current_ip_info, self.current_port)
  File "/app/libexec/warpinator/auth.py", line 78, in update
    self._make_key_cert_pair()
  File "/app/libexec/warpinator/auth.py", line 219, in _make_key_cert_pair
    backend=crypto_default_backend(),
  File "/app/lib/python3.9/site-packages/cryptography/hazmat/backends/__init__.py", line 9, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/app/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/app/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 64, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/app/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._openssl'
```

**Comment by mtwebster** [comment]
Hi, thanks for the work you're doing here. I've been meaning to update it, but haven't had any time recently.

I'm not sure about the crypto error - I don't really know more about that module than what I needed for the semi-boilerplate code I'm using it in.

The closest thing I could find is this:
https://bugs.gentoo.org/803887

I'm not sure if that's even relevant here, though.  When I get a chance I'll test this PR out and try to troubleshoot.

Thanks again

**Comment by bbhtt** [comment]
> I'm not sure if that's even relevant here, though. When I get a chance I'll test this PR out and try to troubleshoot.

No worries, thanks :)

I asked in #pyca about that error, @ Crys, @ Alex_Gaynor there pointed out that I could be missing cffi in the build environment due to this warning `/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cffi_modules'`

But I'm pretty sure cffi is being installed and is available for the build: https://github.com/flathub/org.x.Warpinator/pull/6/commits/072968423ae543500427281c7f4ca633851b2743#diff-d0257e5d025a75782ea14807a4a90dbfeba477a5c523114dcbcc039c844f0624R127, else I think cryptography will fail to build. To make sure I added the cffi module before cryptography and I also updated cryptography to the latest release.

**Comment by bbhtt** [comment]
> Build [101737 successful](https://buildbot.flathub.org/#/builders/32/builds/101737) 

> I could be missing cffi in the build environment due to this warning
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cffi_modules'

Indeed that was the issue, cffi needed to be completely installed before the build of cryptography began. Works now.

**Comment by mtwebster** [comment]
Hi, I took this for a quick spin and it seems to work fine - are you done with it?

**Comment by bbhtt** [comment]
> Hi, I took this for a quick spin and it seems to work fine - are you done with it?

Yea, I'm done. Please let me know if anything else is needed. Thanks.

**Comment by mtwebster** [comment]
Thanks again!

**Pull request merged**
