### PR TITLE
Change application ID to com.linuxmint.Warpinator

### LINKED ISSUE #1: Bug: org.x domain should be com.linuxmint
Hi,

as far as I know this application is not related to the x/x11 project, but to Linux Mint. The naming seems a bit off and should be changed to reflect the proper domain / naming "com.linuxmint.Warpinator".

### PR DESCRIPTION
**Pull request by takluyver**
Closes #1

I don't actually know what's required to change the application ID - this changes all the occurrences in the repository, but I don't know if it needs an admin to do something extra.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
That won't work, you need to re-submit the app with the new app-id and then deprecate this one.

**Comment by takluyver** [comment]
:-(

I'll leave that to the maintainers, then, because obviously I can't deprecate this copy.

**Comment by hfiguiere** [comment]
To deprecate you can do this:

https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life

The the renamed one must be submitted first.

**Comment by hfiguiere** [comment]
btw, what the story behind the need to rename

**Comment by takluyver** [comment]
No idea, though I saw `--own-name=org.x.StatusIcon.warpinator` in the manifest - maybe someone extrapolated from that?

**Pull request closed without merging**
