### PR TITLE
Runtime 43

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
> Build [113243 successful](https://buildbot.flathub.org/#/builders/32/builds/113243) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/110845/org.x.Warpinator.flatpakref
> ```

python-xapp failed to build properly,

**Comment by bbhtt** [comment]
> Build [113243 successful](https://buildbot.flathub.org/#/builders/32/builds/113243) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/110845/org.x.Warpinator.flatpakref
> ```

Any idea why this says `no module xapp`? I looked at the build logs but found nothing, diff-ing the list of files between this and the current published build shows no missing files or anything, only version changes.

There is a warning while building python-xapp but that seems to be an issue with the setuptools version included in the runtime and doesn't cause the build/install to fail as far as I can see.

**Comment by mtwebster** [comment]
Sorry for taking so long here - 

The xapp module is this:
https://github.com/linuxmint/xapp/blob/master/libxapp/xapp-gtk3-module.c

It should be added to the GTK3_MODULES environment variable by an xinit script:
https://github.com/linuxmint/xapp/blob/master/data/80xapp-gtk3-module.sh

It performs a couple of magic adjustments to Gtk like adding an xapp  'Favorites' bookmark into the Gtk file dialog and giving our webapps a bit more reliable control over their taskbar icon in Cinnamon.

I'm guessing there's a way we could force it to load via environment options here but it's pretty pointless - XApp Favorites are stored in gsettings/dconf, and not shared between flatpak and userspace as far as I know.

**Comment by mtwebster** [comment]
bot, build

**Comment by mtwebster** [comment]
Ah sorry I see there are two separate messages at startup.

The 'no module named xapp' is because the build thinks ..../site-packages is a non-standard path - it's only copying the egg file over but not unpacking it.

It looks like people add `--env=PYTHONPATH=...../site-packages` to the finish-args, though they seem to use different paths to get there - some starting at /app, some at /usr. But maybe seeing this will trigger the module actually getting installed? Something new with 3.10?

```
Checking .pth file support in /app/lib/python3.10/site-packages/
/usr/bin/python3 -E -c pass
TEST FAILED: /app/lib/python3.10/site-packages/ does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /app/lib/python3.10/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html#custom-installation-locations
```

**Comment by mtwebster** [comment]
No, that doesn't do anything - adding to finish-args

**Comment by mtwebster** [comment]
Ok it seems to work now (other than the module warning). That warning, it turns out, is caused by the local user's GTK3_MODULES environment variable.  When I run the following, there is no warning:

```
GTK3_MODULES='' flatpak run org.x.Warpinator
```

I'm surprised by this, but I don't work with flatpaks much, so there's probably a reason I'm missing (for inheriting the user's environment).


Let me know if this works for you now, and I'll merge it.

Thanks!

**Comment by bbhtt** [comment]
I don't see any warnings regarding GTK modules.

> Let me know if this works for you now, and I'll merge it.

Yes, seems to work. Thanks for the fix!

> The 'no module named xapp' is because the build thinks ..../site-packages is a non-standard path - it's only copying the egg file over but not unpacking it.

I think it's an issue with setuptools but I'm not sure, maybe https://github.com/pypa/setuptools/issues/3143...

**Comment by mtwebster** [comment]
Ah that warning's just me then, sorry.

I don't know much about python's packaging/building tools, and I'm ok with continuing that trend.

**Pull request merged**
